Description: This template will an OpenSearch Demo with SNSTopic and other parts required for alerting

Parameters:
  EmailParameter:
    Type: String
    Description: Email to send alerts to
    
Resources:
  # -----------------
  # SNS Topic
  # ----------------- 
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: 'os-alert-topic'
      FifoTopic: False
      TopicName: 'os-alert-topic'

  # -----------------
  # SNS Subscription
  # -----------------
  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopic
      Protocol: 'email'
      Endpoint:
        Ref: EmailParameter

  # -----------------
  # IAM Role
  # -----------------
  SNSOSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'SNS_OpenSearch_Role'
      Description: 'IAM role for SNS OpenSearch Alerting'
      # Trust relationships
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - opensearch.amazonaws.com
                - es.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      # Premissions
      Policies:
        # SNS premissions
        - PolicyName: sns
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sns:*'
                Resource: '*'
  # -----------------
  # OpenSearch domain
  # -----------------
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: workshop-domain
      EngineVersion: 'OpenSearch_1.3'
      # Development configuration
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: '1'
        ZoneAwarenessEnabled: false
        InstanceType: 'r6g.large.search'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: '20'
        VolumeType: 'gp2'
      # Node to node encrpytion must be enabled to use the advanced security options
      NodeToNodeEncryptionOptions:
        Enabled: true
      # Encryption at rest must be ebabled to use the advanced security options
      EncryptionAtRestOptions:
        Enabled: true
      # HTTPS must be required to use the advanced security options
      DomainEndpointOptions:
        EnforceHTTPS: true
      # Create a master user with a pre-defined username and password
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: 'OSMasterUser'
          MasterUserPassword: 'AwS#OpenSearch1'
      # Set an access policy open to any AWS resource
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          Effect: 'Allow'
          Principal:
            AWS: '*'
          Action: 'es:*'
          Resource: '*'

  # -----------------
  # Cloud9
  # -----------------
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: 'workshop-cloud9'
      Description: 'Cloud9 development enviorment'
      ImageId: 'amazonlinux-2-x86_64'
      InstanceType: 't2.large'
      AutomaticStopTimeMinutes: '30'
      Repositories: [
        {
          "PathComponent" : '/OpenSearch_API_Examples',
          "RepositoryUrl" : 'https://github.com/ev2900/OpenSearch_API_Examples.git'
        }
      ]
       
Outputs: 
  OSDomainURL:
    Description: 'OpenSearch domain endpoint URL'
    Value: !Join [ "", [ "https://", !GetAtt OpenSearchDomain.DomainEndpoint] ] 
  DashboardURL:
    Description: 'OpenSearch dashboard URL'
    Value: !Join [ "", [ "https://", !GetAtt OpenSearchDomain.DomainEndpoint, "/_dashboards"] ]
  TopicARN:
    Description: 'SNS Topic ARN'
    Value: !Ref SNSTopic
  IAMRoleARN:
    Description: 'IAM Role ARN'
    Value: !GetAtt SNSOSIAMRole.Arn
  UserName:
    Description: 'OpenSearch Dashboard Login UserName'
    Value: 'OSMasterUser'
  Password:
    Description: 'OpenSearch Dashboard Login Password'
    Value: 'AwS#OpenSearch1'