Description: Fluentd Cloud9 development enviorment
Resources:

  # -----------------
  # Cloud9 workspace
  # -----------------
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: 'fluentd-cloud9-opensearch'
      Description: 'Fluentd development enviorment'
      ImageId: 'ubuntu-18.04-x86_64'
      InstanceType: 't2.large'
      AutomaticStopTimeMinutes: '20160'
      Repositories: [
        {
          "PathComponent" : '/Fluentd_Examples',
          "RepositoryUrl" : 'https://github.com/ev2900/Fluentd_Examples.git'
        }
      ]
  
  # -----------------
  #IAM User
  # -----------------
  FluentdIAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: 'Fluentd_User_OpenSearch'

  # Attach an access key to the IAM user
  FluentdIAMUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref FluentdIAMUser

  # -----------------
  # OpenSearch domain
  # -----------------
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: fluentd-domain
      EngineVersion: 'OpenSearch_1.2'
      # Development configuration
      ClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: '1'
        ZoneAwarenessEnabled: false
        InstanceType: 'r6g.large.search'
      EBSOptions:
        EBSEnabled: true
        VolumeSize: '20'
        VolumeType: 'gp2'
      # Node to node encrpytion must be enabled to use the advanced security options
      NodeToNodeEncryptionOptions:
        Enabled: true
      # Encryption at rest must be ebabled to use the advanced security options
      EncryptionAtRestOptions:
        Enabled: true
      # HTTPS must be required to use the advanced security options
      DomainEndpointOptions:
        EnforceHTTPS: true
      # Create a master user with a pre-defined username and password
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: 'OSMasterUser'
          MasterUserPassword: 'AwS#OpenSearch1'
      # Set an access policy open to any AWS resource
      AccessPolicies:
        Version: 2012-10-17
        Statement:
          Effect: 'Allow'
          Principal:
            AWS: '*'
          Action: 'es:*'
          Resource: '*'

Outputs:
  AccessKeyId:
    Description: 'AccessKeyId for IAM user Fluentd_User'
    Value: !Ref FluentdIAMUserAccessKey
  SecretAccessKey:
    Description: 'SecretAccessKey for IAM user Fluentd_User'
    Value: !GetAtt FluentdIAMUserAccessKey.SecretAccessKey
  IAMUserARN:
    Description: 'SecretAccessKey for IAM user Fluentd_User'
    Value: !GetAtt FluentdIAMUser.Arn
  Region:
    Description: 'AWS region'
    Value: !Ref AWS::Region
  UserName:
    Description: 'OpenSearch Dashboard Login UserName'
    Value: 'OSMasterUser'
  Password:
    Description: 'OpenSearch Dashboard Login Password'
    Value: 'AwS#OpenSearch1'
  OSDomainURL:
    Description: 'OpenSearch domain endpoint URL'
    Value: !Join [ "", [ "https://", !GetAtt OpenSearchDomain.DomainEndpoint] ] 
