Description: Fluentd Cloud9 development enviorment
Resources:

  # -----------------
  # Cloud9 workspace
  # -----------------
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: 'fluentd-cloud9'
      Description: 'Fluentd development enviorment'
      ImageId: 'ubuntu-18.04-x86_64'
      InstanceType: 'm5.large'
      AutomaticStopTimeMinutes: '20160'
      Repositories: [
        {
          "PathComponent" : '/Fluentd_Examples',
          "RepositoryUrl" : 'https://github.com/ev2900/Fluentd_Examples.git'
        }
      ]
  # -----------------
  # S3 bucket
  # -----------------
  S3Bucket:
    Type: AWS::S3::Bucket
  
  # -----------------
  #IAM User
  # -----------------
  FluentdIAMUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: 'Fluentd_User'
      Policies:
        - PolicyName: 'Fluentd_S3'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: '*'

  # Attach an access key to the IAM user
  FluentdIAMUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref FluentdIAMUser

Outputs:
  S3BucketName:
    Description: 'S3 bucket name'
    Value: !Ref S3Bucket
  AccessKeyId:
    Description: 'AccessKeyId for IAM user Fluentd_User'
    Value: !Ref FluentdIAMUserAccessKey
  SecretAccessKey:
    Description: 'SecretAccessKey for IAM user Fluentd_User'
    Value: !GetAtt FluentdIAMUserAccessKey.SecretAccessKey
