Description: Fluentd Cloud9 development enviorment
Resources:
  # Cloud9 workspace
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: 'fluentd-cloud9'
      Description: 'Fluentd development enviorment'
      ImageId: 'ubuntu-18.04-x86_64'
      InstanceType: 'm5.large'
      AutomaticStopTimeMinutes: '20160'
      Repositories: [
        {
          "PathComponent" : '/Fluentd_Examples',
          "RepositoryUrl" : 'https://github.com/ev2900/Fluentd_Examples'
        }
      ]
  
  # S3 bucket
  S3Bucket:
    Type: AWS::S3::Bucket
  
  #IAM role
  FluentdIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'Fluentd_Service_Role'
      Description: 'IAM role for Fluentd to send data to S3'
      # Trust relationships
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      # Premissions
      Policies:
        # S3
        - PolicyName: s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: '*'