Description: Create a security group allowing outbound traffic
Parameters:
  VpcIdParameter:
    Type: String
    Description: VpcId for the security group to be applied to
  SecurityGroupNameParameter:
    Type: String
    Description: Security group name
  SecurityGroupDescriptionParameter:
    Type: String
    Description: Security group description
Resources:
  # Create Security Group
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Ref: SecurityGroupNameParameter
      GroupDescription:
        Ref: SecurityGroupDescriptionParameter
      VpcId: 
        Ref: VpcIdParameter
      # Egress rules
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1 
          ToPort: -1
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: 'workshop security group'
  # Add a self reference ingress rule 
  SecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      # Ingress rules
      GroupId: !Ref SecurityGroup
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: !GetAtt SecurityGroup.GroupId
# Outputs for ease of use
Outputs:
  SecurityGroupID:
    Description: Security Group ID
    Value: !Ref SecurityGroup