Description: Create a subnet with IPV4 address space 10.0.0.0/28
Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: '10.0.0.0/28'
      AvailabilityZone: 'us-east-1a'
      VpcId: 'vpc-0169695006c2c5c06'
      Tags:
        - Key: Name
          Value: workshop vpc | subnet a | us-east-1a
# Outputs for ease of use
Outputs:
  VPCId:
    Description: Subnet ID
    Value: !Ref Subnet  