Description: Cloud9 development enviorment
Resources:
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      Name: 'workshop-cloud9'
      Description: 'Cloud9 development enviorment'
      ImageId: 'amazonlinux-2-x86_64'
      InstanceType: 't2.large'
      AutomaticStopTimeMinutes: '30'