name: Upload files to S3

on:
  # Triggers the workflow on push
  push:
    branches: [ main ]
  
  # Allows the workflow to be run manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Upload to S3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Upload OpenSearch_demo.yaml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/OpenSearch\ Demo/OpenSearch_demo.yaml s3://sharkech-public/misc-public/OpenSearch_demo.yaml
        
      - name: Upload OpenSearch_demo_VPC.yaml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/OpenSearch\ Demo/OpenSearch_demo_VPC.yaml s3://sharkech-public/misc-public/OpenSearch_demo_VPC.yaml
        
      - name: Upload OpenSearch_cross_cluster_replication_demo.yaml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/OpenSearch\ Demo/OpenSearch_cross_cluster_replication_demo.yaml s3://sharkech-public/misc-public/OpenSearch_cross_cluster_replication_demo.yaml

      - name: Upload OpenSearch_demo_Cloud9_simple.yaml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/OpenSearch\ Demo/OpenSearch_demo_Cloud9_simple.yaml s3://sharkech-public/misc-public/OpenSearch_demo_Cloud9_simple.yaml

      - name: Upload cloud9_w_OpenSearch_API_repo.yml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/Cloud9/cloud9_w_OpenSearch_API_repo.yml s3://sharkech-public/misc-public/cloud9_w_OpenSearch_API_repo.yml
        
      - name: Upload KDA_studio_kinesis_demo.yaml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/KDA\ Studio\ Demo/KDA_studio_kinesis_demo.yaml s3://sharkech-public/misc-public/KDA_studio_kinesis_demo.yaml
        
      - name: Upload fluentd_cloud9.yml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/Fluentd/fluentd_cloud9.yml s3://sharkech-public/misc-public/fluentd_cloud9.yml
        
      - name: Upload OpenSearch_demo_anomaly_detection.yaml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/OpenSearch\ Demo/OpenSearch_demo_anomaly_detection.yaml s3://sharkech-public/misc-public/OpenSearch_demo_anomaly_detection.yaml
      
      - name: Upload fluentd_cloud9_opensearch.yml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/Fluentd/fluentd_cloud9_opensearch.yml s3://sharkech-public/misc-public/fluentd_cloud9_opensearch.yml
        
      - name: Upload OpenSearch_demo_alerting.yaml to S3
        run: aws s3 cp /home/runner/work/CloudFormation_Examples/CloudFormation_Examples/OpenSearch\ Demo/OpenSearch_demo_alerting.yaml s3://sharkech-public/misc-public/OpenSearch_demo_alerting.yaml
